# App Engine configuration (alternative to Cloud Run)
runtime: nodejs18

env: standard

instance_class: F2

automatic_scaling:
  min_instances: 1
  max_instances: 10
  target_cpu_utilization: 0.6

env_variables:
  DB_USER: 'jc6292'
  DB_HOST: '34.139.8.30'
  DB_NAME: 'proj1part2'
  DB_PASSWORD: '854037'
  DB_PORT: '5432'
  NODE_ENV: 'production'

handlers:
  - url: /.*
    script: auto

